### ISSUE TITLE
Why "camera_height" must divide by 30 !?

### ISSUE THREAD

**Issue by joeking11829** [utiasSTARS/learned_scale_recovery#2]
Hi. Thanks for sharing your great work.

when calculate scale_recovery loss, the "camera_height" must divide by 30. Why !?

Thanks !!

**Comment by joeking11829** [comment]
Hi @brandonwagstaff,

Could you explain this issue ?
Thanks !!

**Comment by brandonwagstaff** [comment]
Hi There,

Our depth predictions are defined to have a minimum and maximum of 0.06 and ~2.67, respectively. Since the real minimum and maximum scene depth values for KITTI are significantly larger than this, we applied an arbitrary scaling factor of 30 to roughly align the scales before applying our scale recovery loss (this allows us to produce scaled predictions without having to drastically shift the scale of the network predictions during training, which could be problematic). 

To account for this scaling factor in our scale recovery loss, we also divide the camera height by 30 to match the scale of the raw predictions. Then, at test time, to produce the metrically scaled predictions, this same scaling factor can be applied (to both the depth and translation predictions). 

Hope this helps!

**Comment by joeking11829** [comment]
> Hi There,
> 
> Our depth predictions are defined to have a minimum and maximum of 0.06 and ~2.67, respectively. Since the real minimum and maximum scene depth values for KITTI are significantly larger than this, we applied an arbitrary scaling factor of 30 to roughly align the scales before applying our scale recovery loss (this allows us to produce scaled predictions without having to drastically shift the scale of the network predictions during training, which could be problematic).
> 
> To account for this scaling factor in our scale recovery loss, we also divide the camera height by 30 to match the scale of the raw predictions. Then, at test time, to produce the metrically scaled predictions, this same scaling factor can be applied (to both the depth and translation predictions).
> 
> Hope this helps!

It does helps !!
Thanks for your reply !!
